### ISSUE TITLE
您好！麻烦请教一个问题。

### ISSUE THREAD

**Issue by jamessmith123456** [ZexuanSun/DTF-Drug-Synergy#1]
请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？
cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by ZexuanSun** [comment]
他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。
所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh

Best，
Zexuan
________________________________
发件人: jamessmith123456 <notifications@github.com>
发送时间: 星期四, 六月 11, 2020 09:06
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Subscribed
主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？
cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by jamessmith123456** [comment]
非常感谢您的回复！
(1) 是的，我多次运行时发现每次CP-WOPT的结果都不一样，存在随机性；
(2) 另外我想请教的问题是，文章中的结果部分，Accuracy、Precision这些指标值是5-fold得来的吗？还是在测试集上(也就是120*2*39个真正的缺失项，非validation data)得来的？ 我在数据集中没找到缺失项对应的synergy得分，以及它们对应的0-1标签；
(3)最后请教一个私人的问题，实在抱歉打扰您，您不方便的话可以不回复，感谢！我想请问这个课题还有继续研究的价值吗，似乎没有太多关于drug-drug-synergy方向的论文出现...


再次感谢您的回复！您的回复帮我解决了问题，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zexuan Sun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 上午9:18
收件人:&nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&gt;;
抄送:&nbsp;"庄驰"<1321985517@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





 他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。 
 所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh 
 
 Best， 
 Zexuan 
 ________________________________ 
 发件人: jamessmith123456 <notifications@github.com&gt; 
 发送时间: 星期四, 六月 11, 2020 09:06 
 收件人: ZexuanSun/DTF-Drug-Synergy 
 抄送: Subscribed 
 主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？ 
 cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by ZexuanSun** [comment]
（2）是5 fold的，不是真正的缺失项，真正缺失项不知道实际值有些metrics没法算，你看的是我arxiv上的draft吧，我那边没有更新到最后accept的版本有些地方没写清楚，然后这里每次算出来也是有随机性的，因为有个dnn，但稳定性还算好我记得
（3）这个我也不晓得啊，我老板当时给我的是这个课题，我就做了这个，我觉得那个只是应用背景在drug synergy，可以变成tensor的背景还是挺多的，那个model的思想其实我感觉可以用在别的地方，如果你指的是drug synergy这个方向那我真的不太清楚，你是做生信的吗，这块我也不晓得，不知道bioinformtics什么比较火，我之前老板dl ml这块用的挺多，但是他后来还叫他别的学生用tensor做别的东西，他之前还让我看transformer什么的说这是dl最新的东西，我没看😂😂😂

PS： 不用这么客气，用“你”就好了😂😂😂
________________________________
发件人: jamessmith123456 <notifications@github.com>
发送时间: 星期四, 六月 11, 2020 20:19
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Zexuan Sun; Comment
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


非常感谢您的回复！
(1) 是的，我多次运行时发现每次CP-WOPT的结果都不一样，存在随机性；
(2) 另外我想请教的问题是，文章中的结果部分，Accuracy、Precision这些指标值是5-fold得来的吗？还是在测试集上(也就是120*2*39个真正的缺失项，非validation data)得来的？ 我在数据集中没找到缺失项对应的synergy得分，以及它们对应的0-1标签；
(3)最后请教一个私人的问题，实在抱歉打扰您，您不方便的话可以不回复，感谢！我想请问这个课题还有继续研究的价值吗，似乎没有太多关于drug-drug-synergy方向的论文出现...


再次感谢您的回复！您的回复帮我解决了问题，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zexuan Sun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 上午9:18
收件人:&nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&gt;;
抄送:&nbsp;"庄驰"<1321985517@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。
所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh

Best，
Zexuan
________________________________
发件人: jamessmith123456 <notifications@github.com&gt;
发送时间: 星期四, 六月 11, 2020 09:06
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Subscribed
主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？
cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by jamessmith123456** [comment]
嘿嘿，老哥，感谢你的回复！你给我点一下，我的疑惑就解答了！
我目前也是刚接触这个方向，所以对tensor以及drug synergy的理解不深，感觉不知从何下手，所以想着向大佬请教下；
老哥，我暂时问题就这么些，非常感谢你的解答和建议, 我再去看看有没有别的文章；后面有问题我再来叨扰老哥!


老哥晚安！加油！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zexuan Sun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 晚上11:02
收件人:&nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&gt;;
抄送:&nbsp;"庄驰"<1321985517@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





 （2）是5 fold的，不是真正的缺失项，真正缺失项不知道实际值有些metrics没法算，你看的是我arxiv上的draft吧，我那边没有更新到最后accept的版本有些地方没写清楚，然后这里每次算出来也是有随机性的，因为有个dnn，但稳定性还算好我记得 
 （3）这个我也不晓得啊，我老板当时给我的是这个课题，我就做了这个，我觉得那个只是应用背景在drug synergy，可以变成tensor的背景还是挺多的，那个model的思想其实我感觉可以用在别的地方，如果你指的是drug synergy这个方向那我真的不太清楚，你是做生信的吗，这块我也不晓得，不知道bioinformtics什么比较火，我之前老板dl ml这块用的挺多，但是他后来还叫他别的学生用tensor做别的东西，他之前还让我看transformer什么的说这是dl最新的东西，我没看😂😂😂 
 
 PS： 不用这么客气，用“你”就好了😂😂😂 
 ________________________________ 
 发件人: jamessmith123456 <notifications@github.com&gt; 
 发送时间: 星期四, 六月 11, 2020 20:19 
 收件人: ZexuanSun/DTF-Drug-Synergy 
 抄送: Zexuan Sun; Comment 
 主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 非常感谢您的回复！ 
 (1) 是的，我多次运行时发现每次CP-WOPT的结果都不一样，存在随机性； 
 (2) 另外我想请教的问题是，文章中的结果部分，Accuracy、Precision这些指标值是5-fold得来的吗？还是在测试集上(也就是120*2*39个真正的缺失项，非validation data)得来的？ 我在数据集中没找到缺失项对应的synergy得分，以及它们对应的0-1标签； 
 (3)最后请教一个私人的问题，实在抱歉打扰您，您不方便的话可以不回复，感谢！我想请问这个课题还有继续研究的价值吗，似乎没有太多关于drug-drug-synergy方向的论文出现... 
 
 
 再次感谢您的回复！您的回复帮我解决了问题，谢谢您！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Zexuan Sun"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年6月11日(星期四) 上午9:18 
 收件人:&amp;nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"庄驰"<1321985517@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 
 
 
 他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。 
 所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh 
 
 Best， 
 Zexuan 
 ________________________________ 
 发件人: jamessmith123456 <notifications@github.com&amp;gt; 
 发送时间: 星期四, 六月 11, 2020 09:06 
 收件人: ZexuanSun/DTF-Drug-Synergy 
 抄送: Subscribed 
 主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？ 
 cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by ZexuanSun** [comment]
好的好的，欢迎随时交流，晚安老哥😴

________________________________
发件人: jamessmith123456 <notifications@github.com>
发送时间: Thursday, June 11, 2020 11:10:04 PM
收件人: ZexuanSun/DTF-Drug-Synergy <DTF-Drug-Synergy@noreply.github.com>
抄送: Zexuan Sun <zexuansun@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


嘿嘿，老哥，感谢你的回复！你给我点一下，我的疑惑就解答了！
我目前也是刚接触这个方向，所以对tensor以及drug synergy的理解不深，感觉不知从何下手，所以想着向大佬请教下；
老哥，我暂时问题就这么些，非常感谢你的解答和建议, 我再去看看有没有别的文章；后面有问题我再来叨扰老哥!


老哥晚安！加油！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zexuan Sun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 晚上11:02
收件人:&nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&gt;;
抄送:&nbsp;"庄驰"<1321985517@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





（2）是5 fold的，不是真正的缺失项，真正缺失项不知道实际值有些metrics没法算，你看的是我arxiv上的draft吧，我那边没有更新到最后accept的版本有些地方没写清楚，然后这里每次算出来也是有随机性的，因为有个dnn，但稳定性还算好我记得
（3）这个我也不晓得啊，我老板当时给我的是这个课题，我就做了这个，我觉得那个只是应用背景在drug synergy，可以变成tensor的背景还是挺多的，那个model的思想其实我感觉可以用在别的地方，如果你指的是drug synergy这个方向那我真的不太清楚，你是做生信的吗，这块我也不晓得，不知道bioinformtics什么比较火，我之前老板dl ml这块用的挺多，但是他后来还叫他别的学生用tensor做别的东西，他之前还让我看transformer什么的说这是dl最新的东西，我没看😂😂😂

PS： 不用这么客气，用“你”就好了😂😂😂
________________________________
发件人: jamessmith123456 <notifications@github.com&gt;
发送时间: 星期四, 六月 11, 2020 20:19
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Zexuan Sun; Comment
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


非常感谢您的回复！
(1) 是的，我多次运行时发现每次CP-WOPT的结果都不一样，存在随机性；
(2) 另外我想请教的问题是，文章中的结果部分，Accuracy、Precision这些指标值是5-fold得来的吗？还是在测试集上(也就是120*2*39个真正的缺失项，非validation data)得来的？ 我在数据集中没找到缺失项对应的synergy得分，以及它们对应的0-1标签；
(3)最后请教一个私人的问题，实在抱歉打扰您，您不方便的话可以不回复，感谢！我想请问这个课题还有继续研究的价值吗，似乎没有太多关于drug-drug-synergy方向的论文出现...


再次感谢您的回复！您的回复帮我解决了问题，谢谢您！




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"Zexuan Sun"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年6月11日(星期四) 上午9:18
收件人:&amp;nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"庄驰"<1321985517@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。
所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh

Best，
Zexuan
________________________________
发件人: jamessmith123456 <notifications@github.com&amp;gt;
发送时间: 星期四, 六月 11, 2020 09:06
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Subscribed
主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？
cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by jamessmith123456** [comment]
老哥老哥，是我呀，我之前向你请教问题的😁😁
老哥，你那个论文里和DeepSynergy这个方法进行了对比，效果比它略好些；我看DeepSynergy这个文章，它自己放出来的结果和老哥你对比用到的结果不一样；它自己的值高一些；
请问老哥，这个是为啥呀？我看数据集是同一份数据集呀，老哥的那个DeepSynergy得分是怎么来的呢？
麻烦老哥啦！嘻嘻~感谢感谢~



---原始邮件---
发件人: "Zexuan Sun"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 晚上11:12
收件人: "ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"jamessmith123456"<1321985517@qq.com&gt;;
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)




 好的好的，欢迎随时交流，晚安老哥😴 
 
 ________________________________ 
 发件人: jamessmith123456 <notifications@github.com&gt; 
 发送时间: Thursday, June 11, 2020 11:10:04 PM 
 收件人: ZexuanSun/DTF-Drug-Synergy <DTF-Drug-Synergy@noreply.github.com&gt; 
 抄送: Zexuan Sun <zexuansun@outlook.com&gt;; Comment <comment@noreply.github.com&gt; 
 主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 嘿嘿，老哥，感谢你的回复！你给我点一下，我的疑惑就解答了！ 
 我目前也是刚接触这个方向，所以对tensor以及drug synergy的理解不深，感觉不知从何下手，所以想着向大佬请教下； 
 老哥，我暂时问题就这么些，非常感谢你的解答和建议, 我再去看看有没有别的文章；后面有问题我再来叨扰老哥! 
 
 
 老哥晚安！加油！ 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"Zexuan Sun"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年6月11日(星期四) 晚上11:02 
 收件人:&amp;nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"庄驰"<1321985517@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 
 
 
 （2）是5 fold的，不是真正的缺失项，真正缺失项不知道实际值有些metrics没法算，你看的是我arxiv上的draft吧，我那边没有更新到最后accept的版本有些地方没写清楚，然后这里每次算出来也是有随机性的，因为有个dnn，但稳定性还算好我记得 
 （3）这个我也不晓得啊，我老板当时给我的是这个课题，我就做了这个，我觉得那个只是应用背景在drug synergy，可以变成tensor的背景还是挺多的，那个model的思想其实我感觉可以用在别的地方，如果你指的是drug synergy这个方向那我真的不太清楚，你是做生信的吗，这块我也不晓得，不知道bioinformtics什么比较火，我之前老板dl ml这块用的挺多，但是他后来还叫他别的学生用tensor做别的东西，他之前还让我看transformer什么的说这是dl最新的东西，我没看😂😂😂 
 
 PS： 不用这么客气，用“你”就好了😂😂😂 
 ________________________________ 
 发件人: jamessmith123456 <notifications@github.com&amp;gt; 
 发送时间: 星期四, 六月 11, 2020 20:19 
 收件人: ZexuanSun/DTF-Drug-Synergy 
 抄送: Zexuan Sun; Comment 
 主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 非常感谢您的回复！ 
 (1) 是的，我多次运行时发现每次CP-WOPT的结果都不一样，存在随机性； 
 (2) 另外我想请教的问题是，文章中的结果部分，Accuracy、Precision这些指标值是5-fold得来的吗？还是在测试集上(也就是120*2*39个真正的缺失项，非validation data)得来的？ 我在数据集中没找到缺失项对应的synergy得分，以及它们对应的0-1标签； 
 (3)最后请教一个私人的问题，实在抱歉打扰您，您不方便的话可以不回复，感谢！我想请问这个课题还有继续研究的价值吗，似乎没有太多关于drug-drug-synergy方向的论文出现... 
 
 
 再次感谢您的回复！您的回复帮我解决了问题，谢谢您！ 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 
 发件人:&amp;amp;nbsp;"Zexuan Sun"<notifications@github.com&amp;amp;gt;; 
 发送时间:&amp;amp;nbsp;2020年6月11日(星期四) 上午9:18 
 收件人:&amp;amp;nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&amp;amp;gt;; 
 抄送:&amp;amp;nbsp;"庄驰"<1321985517@qq.com&amp;amp;gt;;"State change"<state_change@noreply.github.com&amp;amp;gt;; 
 主题:&amp;amp;nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 
 
 
 他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。 
 所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh 
 
 Best， 
 Zexuan 
 ________________________________ 
 发件人: jamessmith123456 <notifications@github.com&amp;amp;gt; 
 发送时间: 星期四, 六月 11, 2020 09:06 
 收件人: ZexuanSun/DTF-Drug-Synergy 
 抄送: Subscribed 
 主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1) 
 
 
 请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？ 
 cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！

**Comment by ZexuanSun** [comment]
1.我重新跑了一遍，deepsynergy那个也是一样的DNN跑出来结果每次都不一样的，但是差不太多
2.deepsynergy跟DTF结果是similar也没有谁好谁坏吧，最后的版本里面做了t-test，给出的结论是similar，arxiv上我那个不是终稿，我一直没更新....
________________________________
发件人: jamessmith123456 <notifications@github.com>
发送时间: Monday, July 6, 2020 1:46:30 AM
收件人: ZexuanSun/DTF-Drug-Synergy <DTF-Drug-Synergy@noreply.github.com>
抄送: Zexuan Sun <zexuansun@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


老哥老哥，是我呀，我之前向你请教问题的😁😁
老哥，你那个论文里和DeepSynergy这个方法进行了对比，效果比它略好些；我看DeepSynergy这个文章，它自己放出来的结果和老哥你对比用到的结果不一样；它自己的值高一些；
请问老哥，这个是为啥呀？我看数据集是同一份数据集呀，老哥的那个DeepSynergy得分是怎么来的呢？
麻烦老哥啦！嘻嘻~感谢感谢~



---原始邮件---
发件人: "Zexuan Sun"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 晚上11:12
收件人: "ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"jamessmith123456"<1321985517@qq.com&gt;;
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)




好的好的，欢迎随时交流，晚安老哥😴

________________________________
发件人: jamessmith123456 <notifications@github.com&gt;
发送时间: Thursday, June 11, 2020 11:10:04 PM
收件人: ZexuanSun/DTF-Drug-Synergy <DTF-Drug-Synergy@noreply.github.com&gt;
抄送: Zexuan Sun <zexuansun@outlook.com&gt;; Comment <comment@noreply.github.com&gt;
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


嘿嘿，老哥，感谢你的回复！你给我点一下，我的疑惑就解答了！
我目前也是刚接触这个方向，所以对tensor以及drug synergy的理解不深，感觉不知从何下手，所以想着向大佬请教下；
老哥，我暂时问题就这么些，非常感谢你的解答和建议, 我再去看看有没有别的文章；后面有问题我再来叨扰老哥!


老哥晚安！加油！


------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"Zexuan Sun"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2020年6月11日(星期四) 晚上11:02
收件人:&amp;nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"庄驰"<1321985517@qq.com&amp;gt;;"State change"<state_change@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





（2）是5 fold的，不是真正的缺失项，真正缺失项不知道实际值有些metrics没法算，你看的是我arxiv上的draft吧，我那边没有更新到最后accept的版本有些地方没写清楚，然后这里每次算出来也是有随机性的，因为有个dnn，但稳定性还算好我记得
（3）这个我也不晓得啊，我老板当时给我的是这个课题，我就做了这个，我觉得那个只是应用背景在drug synergy，可以变成tensor的背景还是挺多的，那个model的思想其实我感觉可以用在别的地方，如果你指的是drug synergy这个方向那我真的不太清楚，你是做生信的吗，这块我也不晓得，不知道bioinformtics什么比较火，我之前老板dl ml这块用的挺多，但是他后来还叫他别的学生用tensor做别的东西，他之前还让我看transformer什么的说这是dl最新的东西，我没看😂😂😂

PS： 不用这么客气，用“你”就好了😂😂😂
________________________________
发件人: jamessmith123456 <notifications@github.com&amp;gt;
发送时间: 星期四, 六月 11, 2020 20:19
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Zexuan Sun; Comment
主题: Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


非常感谢您的回复！
(1) 是的，我多次运行时发现每次CP-WOPT的结果都不一样，存在随机性；
(2) 另外我想请教的问题是，文章中的结果部分，Accuracy、Precision这些指标值是5-fold得来的吗？还是在测试集上(也就是120*2*39个真正的缺失项，非validation data)得来的？ 我在数据集中没找到缺失项对应的synergy得分，以及它们对应的0-1标签；
(3)最后请教一个私人的问题，实在抱歉打扰您，您不方便的话可以不回复，感谢！我想请问这个课题还有继续研究的价值吗，似乎没有太多关于drug-drug-synergy方向的论文出现...


再次感谢您的回复！您的回复帮我解决了问题，谢谢您！




------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
发件人:&amp;amp;nbsp;"Zexuan Sun"<notifications@github.com&amp;amp;gt;;
发送时间:&amp;amp;nbsp;2020年6月11日(星期四) 上午9:18
收件人:&amp;amp;nbsp;"ZexuanSun/DTF-Drug-Synergy"<DTF-Drug-Synergy@noreply.github.com&amp;amp;gt;;
抄送:&amp;amp;nbsp;"庄驰"<1321985517@qq.com&amp;amp;gt;;"State change"<state_change@noreply.github.com&amp;amp;gt;;
主题:&amp;amp;nbsp;Re: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)





他这个东西有一定的随机性，因为CP-WOPT那个优化算法每次结果都不一样，他的目标函数只是逼近原来的tensor，逼近的可能有很多种。
所以我觉得这东西也有点离谱，这样再加一个DNN，又加了一个随机性，这样预测最后跑出来的结果也有随机性，但是有些pair是经常出现在最后的结果里的我记得。😑😑😑综上我觉得这个model的稳定性就有点离谱。见笑了不好意思hhhh

Best，
Zexuan
________________________________
发件人: jamessmith123456 <notifications@github.com&amp;amp;gt;
发送时间: 星期四, 六月 11, 2020 09:06
收件人: ZexuanSun/DTF-Drug-Synergy
抄送: Subscribed
主题: [ZexuanSun/DTF-Drug-Synergy] 您好！麻烦请教一个问题。 (#1)


请问项目文件夹下的./data_sets/final_data/drug_a.csv, drug_b.csv和cell_line.csv是怎么得来的呢？是直接运行cpwopt_final.m得来的吗？
cpwopt_final.m中，将fold_0_final.csv中的项在P矩阵中设置为0? 我运行cpwopt_final.m得到的特征值，跟./data_sets/final_data/drug_a.csv, drug_b.csv和fold_0_final.csv中的不一样；想不出为啥，能不能请教您一下，感谢！
