### ISSUE TITLE
Some problems about the code.

### ISSUE THREAD

**Issue by ZJMHub** [ZexuanSun/DTF-Drug-Synergy#2]
Dear Dr. Sun Zexuan
I am a post graduate student. I am interested in your DTF model, but I don’t understand some parts of the code very well, and I can’t find the source in the paper. I hope you can answer it.
![1628777919(1)](https://user-images.githubusercontent.com/19562428/129213150-d2aaac76-47dc-4bef-8f17-b224b8df47d9.png)
Can you explain what is the purpose of this code and how its parameters are determined?
Hope to get your answer
Thank you and regrads

**Comment by ZexuanSun** [comment]
For this dataset, I get the indices of the missing values using Python. In order to run the algorithm in Matlab, the missing of the P tensor should be set as zero. This part of code is setting the missing part as zeros.

**Comment by ZJMHub** [comment]
> For this dataset, I get the indices of the missing values using Python. In order to run the algorithm in Matlab, the missing of the P tensor should be set as zero. This part of code is setting the missing part as zeros.

Thank you for your reply. At the same time, I also found a problem when I tried to run the matlab code, that is, when the amount of drugs or cell line increases sharply, the memory that needs to be run increases rapidly. Can you have a better and faster solution?

**Comment by ZexuanSun** [comment]
I am sorry that I do not have a better solution.

**Comment by ZJMHub** [comment]
> I am sorry that I do not have a better solution.

Thank you so much for your help!
